name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up API tokens
      run: |
        echo "TOKEN_API=${{ secrets.TOKEN_API }}" >> $GITHUB_ENV
        echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

    - name: Deploy to GitHub Pages
      run: |
        echo "Deployment successful"