name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject Spoonacular API Key into JavaScript
        run: |
          sed -i 's|SPOONACULAR_API_PLACEHOLDER|${{ secrets.SPOONACULAR_API }}|g' script.js

      - name: Deploy to GitHub Pages
        run: echo "✅ Deployment successful!"
