name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API Keys into JavaScript
        run: |
          sed -i 's|API_TOKEN_PLACEHOLDER|${{ secrets.API_TOKEN }}|g' auth.js
          sed -i 's|TOKEN_API_PLACEHOLDER|${{ secrets.TOKEN_API }}|g' script.js

      - name: Deploy to GitHub Pages
        run: echo "✅ Deployment successful!"
