name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug Secrets Presence
      run: |
        if [[ -z "${{ secrets.API_TOKEN }}" ]]; then
          echo "❌ API_TOKEN is missing!"
          exit 1
        else
          echo "✅ API_TOKEN is set."
        fi

        if [[ -z "${{ secrets.TOKEN_API }}" ]]; then
          echo "❌ TOKEN_API is missing!"
          exit 1
        else
          echo "✅ TOKEN_API is set."
        fi

    - name: Deploy to GitHub Pages
      run: echo "✅ Deployment successful!"
